### ISSUE TITLE
Add content to the "about section" on the page

### ISSUE THREAD

**Issue by morchickit** [okfn/opendataday#103]
-  history of the event ?
- who is behind the event?
- how can i join?

**Comment by Hazwany** [comment]
I would also suggest:

- what are ODD core values? or what makes ODD important?

**Comment by morchickit** [comment]
Open Data Day is an annual celebration of open data all over the world. For the fifth time in history, groups from around the world will create local events on the day where they will use open data in their communities. It is an opportunity to show the benefits of open data and encourage the adoption of open data policies in government, business and civil society. 

This is a real bottom-up initiative that is coordinated on this mailing list [open-data-day@googlegroups.com]. This year, Open knowledge International has helped to build the Open Data Day website and is giving mini grants with SPARC and HIVOS to help and get events up and running. Anyone can contribute to Open Data Day either by using the list or contribute to the GitHub repo. 

How can you join?
Easy, everyone can join. 
 - Register your event here 
 - Register to the mailing list
 - Translate this page to you language 
 - Contribute to the Github repo

Open Data Day values 
- Open to everyone - from citizens to government officials - everyone are welcome to join
- Participatory - allows everyone to voice their opinions in a constructive manner 
- Open - All outputs are open to everyone to use and re-use

**Comment by morchickit** [comment]
Done.
