### ISSUE TITLE
Create a new logo to Open Data Day 

### ISSUE THREAD

**Issue by morchickit** [okfn/opendataday#105]
Current logo has the word Hackathon in it - 
![image](https://cloud.githubusercontent.com/assets/3273659/20110199/503269e6-a5db-11e6-8544-2819f9046f57.png)

OK Japan created this logo generator in the past - http://logo.odd.okfn.jp/ It will be nice to have the new logo for the International Open Data Day in the same spirit.

**Comment by morchickit** [comment]
I emailed, OK Japan (Masahiko) and I am waiting for a reply.

**Comment by morchickit** [comment]
Done. @smth can I close this? Should we upload the logo to assets?

**Comment by smth** [comment]
If we are uploading it to be shared, we might want to consider alternative version, that contains some text. I think the minimal version works fine on the website though, because it is surrounded by the words "Open Data Day".

**Comment by morchickit** [comment]
Ok. If we can do it in a hour work (or less, let me know).

**Comment by smth** [comment]
I have just made a quick full logo, which can now be found [here](https://a.okfn.org/img/opendataday/logo-full.svg). The minimal one is [here](https://a.okfn.org/img/opendataday/logo-minimal.svg)
