### ISSUE TITLE
Blog post announcing the Mini Grant scheme

### ISSUE THREAD

**Issue by morchickit** [okfn/opendataday#108]
- [x] Write draft

- [x] Send draft to Hivos and SPARC

- [x]  Publish on the blog 

- [x]  Promote on Social Media, Forum and Friends

**Comment by morchickit** [comment]
Base on this doc- https://docs.google.com/document/d/1tFxjWUP70g8krZJj8fEJLqeNBpHGGmP9CZEG00kmVaY/edit

**Comment by sdopoku** [comment]
Blog post ready and can be found here: https://docs.google.com/document/d/1MiOOlqF9suAmZ3-bRjXySKOyl1jRBCYu-4I1Rmlx9_k/edit#heading=h.ls7ye6t9ai9f.  Comments welcome.
