### ISSUE TITLE
Re-Write the Get Started section on the page

### ISSUE THREAD

**Issue by morchickit** [okfn/opendataday#109]
- [x]  Remove links to the wiki

- [x] Connect to the event's idea and the mailing list

**Comment by morchickit** [comment]
@smth - can we link to the mailing list on the homepage? address - open-data-day@googlegroups.com 

Events ideas text is here - https://docs.google.com/a/okfn.org/document/d/1iU5xirkL7-wZeXatRdjpR4pm1NiD8UF9s7VJqGMsf74/edit?usp=drive_web

**Comment by smth** [comment]
Is that the same as https://groups.google.com/forum/#!forum/open-data-day ?

**Comment by morchickit** [comment]
yes, that's the same!
