### ISSUE TITLE
Social media strategy for the mini grants

### ISSUE THREAD

**Issue by morchickit** [okfn/opendataday#111]
Think of how to spread the word about the mini-grants:

- [x]  List of all relevant Facebook groups
- [x] Tweets list

**Comment by Hazwany** [comment]
I believe the shared tips from this [blog](https://blog.bufferapp.com/how-often-post-social-media) might be useful for disseminating info about the mini-grants i.e number of postings to Facebook groups and tagging some organisation in Twitter.

**Comment by Hazwany** [comment]
If there is a planning for YouTube video about ODD, that would be great. Audio+visual content is an added value to attract visitors.

**Comment by morchickit** [comment]
Mini grant period ended!
