### ISSUE TITLE
Refresh the text for the personas 

### ISSUE THREAD

**Issue by morchickit** [okfn/opendataday#123]
- Citizens - We need you the most. If it wasn’t for you, this whole thing wouldn’t be happening. We need ideas, cheerleaders, and friends to spread the word.

- Public Servants - Your input and context can help us to make government data better. Come converse and learn.

- Designers - Help us make open data relatable, so more people will use it and understand it. 

- Developers - Use your skills to develop solutions that can help solve important societal issues 

- Statisticians - Use your skills to help understand the data and get important insights from it.

**Comment by morchickit** [comment]
@smth can I close this?

**Comment by smth** [comment]
Yup.
