### ISSUE TITLE
Add map overlay for # of events registered so far

### ISSUE THREAD

**Issue by danfowler** [okfn/opendataday#131]
@smth @morchickit wants an overlay for the # of events registered.  Maybe something like [ 9 events registered ] somewhere hovering over the map.  Given this site is localized, we would need to add translations, I think, for the phrase "events registered" (e.g. "eventos registrados").

Also, where on the map should it go?

**Comment by smth** [comment]
I've added a placeholder [here](https://github.com/okfn/opendataday/blob/master/templates/home.html#L121), so you just need to replace the `x`.

**Comment by danfowler** [comment]
Thanks @smth I've added a PR to populate it.
