### ISSUE TITLE
Add LICENSE.md

### ISSUE THREAD

**Issue by danfowler** [okfn/opendataday#143]
What is the license for this website?

**Comment by morchickit** [comment]
Yes, I am wondering if we can do just creative commons 4.0 with no
attribution. There are no OKI logos here, so should be good.

**Comment by nvitucci** [comment]
For my use case, I think even CC-BY would be fine. Would a footer such as "Based on the original design from https://github.com/okfn/opendataday" be enough?

**Comment by nvitucci** [comment]
@morchickit Any news about this?

**Comment by morchickit** [comment]
DONE. Added CC 00.
