### ISSUE TITLE
Set GitHub topics

### ISSUE THREAD

**Issue by Daniel-Mietchen** [okfn/opendataday#148]
As per
https://help.github.com/articles/about-topics/ .

Suggestions:
- https://github.com/search?q=topic%3Aopendata
- https://github.com/search?q=topic%3Aopen-data
- https://github.com/search?q=topic%3Aopendataday
- perhaps https://github.com/search?q=topic%3Aopen-data-day

**Comment by danfowler** [comment]
Thanks @Daniel-Mietchen I've tagged as you suggested!  That was an easy one :)
