### ISSUE TITLE
Provide a checklist for event organizers

### ISSUE THREAD

**Issue by Daniel-Mietchen** [okfn/opendataday#150]
Every year, organizers of Open Data Day events are being faced with issues that are not too specific to their events and have come up before, e.g. finding a location and budget, arranging for food, name tags and wifi, getting the word out, etc.

It would be very useful to have a checklist of such things somewhere that can be easily forked for customization to an event at hand.

**Comment by tlacoyodefrijol** [comment]
@Daniel-Mietchen we're working on a guide for Open Data Day organizers. We'll open it for comments and then upload here, in case you want to participate.

**Comment by Daniel-Mietchen** [comment]
Here's a good one, based on 5 ODDs: https://hackathon.guide/ .
A simpler one, based on ODD 2017, is in https://github.com/sparcopen/do-a-doathon/tree/master/guide .

**Comment by tlacoyodefrijol** [comment]
This is brilliant! We'll get to work and definitely use and reference these resources.

**Comment by tlacoyodefrijol** [comment]
@Daniel-Mietchen we created a guide for ODD. It's open for comments and linked to the resources you shared.
