### ISSUE TITLE
events do not display on map

### ISSUE THREAD

**Issue by skasberger** [okfn/opendataday#151]
the single event does not show up as a baloon or so on the map. it only shows the agreggated number of events in big scale zoom levels.

**Comment by morchickit** [comment]
@danfowler ideas? @skasberger - it looks to me that there might be duplicatees for the Austrian events? I can see ballons though for single events...

**Comment by skasberger** [comment]
@morchickit there are re-occuring locations, but different events happening inside it.

**Comment by danfowler** [comment]
Yeah, I do see that these events are separated, but you do have to zoom quite deep to pick apart two events in the same city.  We could possibly tweak the clustering radius or experiment with a better UI for showing events in the same vicinity.

**Comment by danfowler** [comment]
We could possibly also combine events that have the same or similar coordinates, and display a combined popup description.

**Comment by skasberger** [comment]
sorry, i think i have just not seen the icon/balloon in the first place. now i get it. but my places are shifted to the right (~50m). i did pick the coordinates from google maps, was that wrong?

**Comment by danfowler** [comment]
Good question.  Google Maps should be fine.  I guess it depends on whether Google Maps and Mapbox use the same [datum](https://en.wikipedia.org/wiki/Geodetic_datum) which I think they do.

**Comment by tlacoyodefrijol** [comment]
@skasberger was this issue solved?

**Comment by skasberger** [comment]
@tlacoyodefrijol yes.

**Comment by tlacoyodefrijol** [comment]
Closing issue now
