### ISSUE TITLE
Map not showing on Chromium 55

### ISSUE THREAD

**Issue by kynan** [okfn/opendataday#155]
Chromium 55.0.2883.87 Built on Ubuntu , running on LinuxMint 18.1 (64-bit)

I get the following errors in the JS console:
```
Error: Failed to initialize WebGL
    at e._setupPainter (map.js:1100)
    at new e (map.js:168)
    at map.js:4
Evented.fire @ evented.js:91
```
```
Uncaught TypeError: Cannot read property 'resize' of undefined
    at e.resize (map.js:362)
    at new e (map.js:197)
    at map.js:4
```
```
Uncaught TypeError: Cannot read property 'resize' of undefined
    at e.resize (mapbox-gl.js:211)
    at e._onWindowResize (mapbox-gl.js:211)
```
```
Uncaught TypeError: Cannot read property 'resize' of undefined
    at e.resize (map.js:362)
    at e._onWindowResize (map.js:1254)
```

**Comment by danfowler** [comment]
Thanks.  This works for me on "Version 58.0.3029.0 (Developer Build) (64-bit)
Get help with Chromium"

I know it's old, but have you seen this thread?

https://askubuntu.com/questions/636322/webgl-doesnt-work-in-chromium-on-ubuntu

**Comment by kynan** [comment]
It was [a generic WebGL issue](https://bugs.chromium.org/p/chromium/issues/detail?id=660493#c7), nothing do with the OpenDataDay page.

**Comment by danfowler** [comment]
Thanks @kynan !
