### ISSUE TITLE
Problem with Russian translation

### ISSUE THREAD

**Issue by Sadless74** [okfn/opendataday#187]
Hi last week I updated Russian version so I did a pull request.
tlacoyodefrijol merge its. Thank you tlacoyodefrijol 

On the language menu on the website opendataday.org have a choice of RU.
But when I choose Russian, the page is updated and remains in English.

Translation from English into Russian did according to the instructions.

Can someone check what the problem might be?

**Comment by tlacoyodefrijol** [comment]
Hi @Sadless74. I just accepted your PRs but it seems like it still isn't showing all the content in Russian. I'll look into fixing this, since all the content is ready.

**Comment by Sadless74** [comment]
I found my mistake and torrect it.
Name was contents_ru.lr, but need name contents+ru.lr
Please merge https://github.com/okfn/opendataday/pull/191
Thank you tlacoyodefrijol for your attention.
