### ISSUE TITLE
Misplaced Minna Niger State Nigeria

### ISSUE THREAD

**Issue by millette** [okfn/opendataday#194]
Looking at the map
https://render.githubusercontent.com/view/geojson?url=https://raw.githubusercontent.com/millette/jido2018/master/jido2018.json
I'm under the impression there was a typo for Minna Niger State Nigeria.

Using https://mynasadata.larc.nasa.gov/latitudelongitude-finder/ I found these latitude and longitude:
9.583555, 6.546316

But the spreadsheet has an extra 9 prefix: 99.583555.

**Comment by tlacoyodefrijol** [comment]
Thank you @millette, each organizer adds the lat long for their events and we've noticed some errors like this. Thank you for the heads up, changing it now.
