### ISSUE TITLE
Open the events data

### ISSUE THREAD

**Issue by millette** [okfn/opendataday#195]
Hey, what about making the events data open? A nice geojson like https://github.com/millette/jido2018/blob/master/jido2018.json would be great :-)

In my unofficial version, I filtered out any event without proper coordinates.

**Comment by millette** [comment]
In any case... http://jido2018.waglo.com/#mapid

**Comment by svanderwaal** [comment]
For now, we've uploaded the current snapshot of all the events submitted so far here:  https://old.datahub.io/dataset/open-data-day-events-2018

**Comment by tuukka** [comment]
Found a nice place to host a live copy of @millette's script for free: https://repl.it/@tuukkah/opendataday-events

Direct link to the always up-to-date GeoJSON: https://opendataday-events--tuukkah.repl.co/
