### ISSUE TITLE
2019 events list

### ISSUE THREAD

**Issue by harry-wood** [okfn/opendataday#203]
What's the plan for the 2019 website?
I see the site has been updated to show the 2019 date. Some other quick updates are needed:

* If we're keeping the map of last year's events for a little while longer, then instead of "406 events registered" it should say "We had 406 events last year".

* "Register your event here" currently links to a now google form for adding an event last year (at least it has been closed!). A minimal change would be to remove this button for the moment.

I'd suggest we do those things ^^^  and then...

What's the plan? Setting up a google form -> google spreadsheet again, or something better perhaps? There's a few other issues related to this. Desire for the adding process to be simple. https://github.com/okfn/opendataday/issues/91  Desire for open data https://github.com/okfn/opendataday/issues/195 (naturally!). I think it's desirable to have the ability to fix the data by pull request i.e. have it live in github, but ... pros & cons ... anyway I'm not sure if anyone's currently planning anything, or working on anything for 2019.

**Comment by tlacoyodefrijol** [comment]
Hi @harry-wood Sorry for the delayed response. We're currently preparing the new edits for 2019. I'll make the suggested changes right now, besides all the other changes we have planned. 

We will continue to use a google form. We've analyzed other options and with all its limitations, this is the simplest, most effective solution to generate the geojson we use for the events map. Issue #195 was responded to, although we still need to clean up the data for other years in order for it to be useful.

**Comment by tlacoyodefrijol** [comment]
@harry-wood The events map is now ready for new submissions. You can add yous if you are planning an Open Data Day event this year
