### ISSUE TITLE
Research Open Data

### ISSUE THREAD

**Issue by Urbanomatos** [okfn/opendataday#225]
Hello all,
I'm a PhD student at Laval University, researching the Open Data ecosystem.
I'm also participating in an Open Data survey by my advisor, in which we will interview people who have participated in or organised Hackathons.
This interview is scheduled to last one hour.
I would like to know in the group if there are people interested in participating in the interviews, and if they can indicate other people who can participate.
Thank you very much in advance

**Comment by tlacoyodefrijol** [comment]
Hi @Urbanomatos, sorry for the late response. If it's still useful, you could post this request to the [google group](https://groups.google.com/forum/#!forum/open-data-day). I'm sure you'll get responses to get interviews.

**Comment by Urbanomatos** [comment]
Hi Oscar,
Ok, thank you

Salutations cordiales,

[cid:image002.png@01D5828B.5221F5C0]

Urbano Cerqueira Matos Jr , Dt.P., M.Sc.
Étudiant au doctorat / Doctoral student
Faculté des Sciences de l’Administration
Systèmes d’Information Organisationnels

Pavillon Palasis Prince, 6221
2325 rue de la Terrasse, Québec, QC G1V 0A6, Canada

Téléphone local     : +1 (418) 656 2131 poste 40-8242
Téléphone mobile  : +1 (581) 748 9290
Whatsapp                :+55 71 9 8834 1915



De : Oscar Montiel <notifications@github.com>
Envoyé : 14 octobre 2019 12:03
À : okfn/opendataday <opendataday@noreply.github.com>
Cc : Urbano Cerqueira Matos Junior <urbano.matos.1@ulaval.ca>; Mention <mention@noreply.github.com>
Objet : Re: [okfn/opendataday] Research Open Data (#225)


Hi @Urbanomatos<https://github.com/Urbanomatos>, sorry for the late response. If it's still useful, you could post this request to the google group<https://groups.google.com/forum/#!forum/open-data-day>. I'm sure you'll get responses to get interviews.
