### ISSUE TITLE
Logo generator not working

### ISSUE THREAD

**Issue by aplannersguide** [okfn/opendataday#261]
I'm trying to create a logo for Chattanooga's event but can't get the [logo generator](http://odd.structure-and-representation.com/) to work. I thought I would mention it incase others are also having trouble.

**Comment by StephenAbbott** [comment]
Thanks for flagging this, @aplannersguide. I'll reach out to Yuichi who created the generator https://github.com/n1n9-jp

**Comment by StephenAbbott** [comment]
Hi @aplannersguide. The issue with the logo generator has been fixed now. Please try it again (you might have to refresh a few times to get it working once) http://odd.structure-and-representation.com/
