### ISSUE TITLE
Bad label of event on map

### ISSUE THREAD

**Issue by pyrog** [okfn/opendataday#289]
Label of an event on the map is it's date, not it's title.

<img width="50%" alt="Title on map" src="https://user-images.githubusercontent.com/2158081/105965865-3d942280-6084-11eb-8043-f4d9988340f3.png">

**Comment by StephenAbbott** [comment]
This is expected behaviour. The [Open Data Day map](https://opendataday.org/#map) shows the time/date that an event was submitted to the events spreadsheet and users can click on the map marker to see more details about the title/location/organiser of the event

**Comment by pyrog** [comment]
Ok, but unusual and not user friendly 😉

**Comment by StephenAbbott** [comment]
@pyrog Event labels on the Open Data Day map have now been changed https://opendataday.org/

**Comment by pyrog** [comment]
Thank you 😃
