### ISSUE TITLE
Missing translation: ja

### ISSUE THREAD

**Issue by pyrog** [okfn/opendataday#294]
Menu
https://github.com/okfn/opendataday/blob/eb72a6e083e616c5d61eb84d5d867bafe2964b8f/databags/main-nav.ini#L43-L48

Footer
https://github.com/okfn/opendataday/blob/eb72a6e083e616c5d61eb84d5d867bafe2964b8f/databags/global-content.ini#L25-L27

**Comment by StephenAbbott** [comment]
Hi @pyrog. Thanks for pointing these out. We rely on our community and network to help donate their time to translate the opendataday.org website. Well spotted that these menu and footer items have not been translated into Japanese.

If it helps, here is a Google doc listing all the translations that we hope people have time to donate to us including Japanese
https://docs.google.com/document/d/19MXh6xNDp2nN2_SKSeBpwYYNSUYXZKmxEGbF0U_85oE/edit

We have no Japanese speakers on our immediate Open Knowledge Foundation team so won't be able to translate these ourselves. I'll close the issue for now.
