### ISSUE TITLE
Broken page layout in Bresilian

### ISSUE THREAD

**Issue by pyrog** [okfn/opendataday#299]
Hi,

The layout is broken in Bresilian:

<img width="50%" alt="PT-BR" src="https://user-images.githubusercontent.com/2158081/106311322-4132cf80-6265-11eb-807d-5f89fff71f59.png">

<img width="50%" alt="English" src="https://user-images.githubusercontent.com/2158081/105964271-3ec45000-6082-11eb-8438-62702de17a33.png">

Also, the translation don't seem up to date 🤔

**Comment by StephenAbbott** [comment]
The layout has now been changed and the translation has been updated so I'm closing this issue.
