### ISSUE TITLE
Translation not up to date in Taiwanese

### ISSUE THREAD

**Issue by pyrog** [okfn/opendataday#300]
See date in the right pane:

<img width="1266" alt="ZH-TW" src="https://user-images.githubusercontent.com/2158081/106311734-e5b51180-6265-11eb-824d-1e77815b84db.png">

**Comment by StephenAbbott** [comment]
Updated Taiwanese Mandarin translation has now been submitted by our community and the translation is updated https://opendataday.org/zh_tw/
