### ISSUE TITLE
Update pt_br translation

### ISSUE THREAD

**Issue by trevineju** [okfn/opendataday#340]
Hello! Just informing I'm working on fixing problems on pt_br version and updating it

**Comment by trevineju** [comment]
Still need to translate...

- Short term: 
a) contents+pt_br: exchange "coming soon" to detailed information once is published
b) main_nav [pt_br] section: when events-2022.json is created

- Middle term:
a) global_content [pt_br] section, item **support_scheme_logos**: update it to 2022
b) reports_content [pt_br] section, item **preamble**: update it to 2022
(in both cases, since its about thanking funders, I understood it's only updated after the event or when new grant scheme is published)

**Comment by trevineju** [comment]
And I need help to discover how to update the "OPEN DATA DAY MINI-GRANTS" title in homepage since there is no reference to it in contents.lr (general file).
![Screenshot from 2022-01-18 20-44-51](https://user-images.githubusercontent.com/44185775/150037131-b6f0835e-58a7-459d-af06-ca3515d3b267.png)

**Comment by aivuk** [comment]
It is "hardcoded" in the template https://github.com/okfn/opendataday/blob/master/templates/home.html#L24, you can't changed it easily. Just if we create a new block for it.

**Comment by trevineju** [comment]
Thanks @aivuk! That would be great, I guess. I mean I don't think the English title spoil the audience's understanding, especially because the description is fully translated. But for the purposes of making everything consistent, it would be a nice change. Should I open an issue to suggest this? Or should I wait for Stephen come have a look here first?

**Comment by augusto-herrmann** [comment]
In the past years we have been using "[minibolsas](https://github.com/okfn/opendataday/blob/70ceb0e2d1f3b1e5f87853bdc6069fb2d33b38d0/content/contents+pt_br.lr#L30)" as a translation for "mini-grants".

**Comment by augusto-herrmann** [comment]
Since PR #348 is merged I think this issue is ready to be closed.

Thanks for taking care of the translation this year, @trevineju !
