### ISSUE TITLE
Update ODD branding to match new guidelines

### ISSUE THREAD

**Issue by lucpretti** [okfn/opendataday#374]
We need to update the visual positioning of the ODD to align with the new brand standards of OKFN projects. In this case, it's a simple change: just update the main assets and change the site's theme colours.

This is the update banner (which should be also reflected in Open Graph and social media cards):
![odd-banner-2023](https://user-images.githubusercontent.com/8523847/217264573-e4a20fdf-ddd3-4ecf-9172-08298d271adc.png)

The ODD logo colours should be updated using the following codes:

O
style="fill:rgb(224,119,255);"

D
style="fill:rgb(229,252,66);"

D
style="fill:rgb(3,209,255);"

The final result should look like this:
![Screenshot 2023-02-07 at 15 08 47](https://user-images.githubusercontent.com/8523847/217268085-b88ba697-439e-4b34-9ff6-49162f458536.png)

All colours across the website should be updated as follows:

- blue - #0086ff turns into #00D1FF
- purple - #9b20dc turns into #E077FF
- green - #48c0ac turns into #AEFFEC
- yellow - #ffb900 turns into #E4FF36
- red - #ff4900 turns into #FF80DB
- secondary blue - #0086ff turns into #9ab201

The OKFN logo in the footer should be replaced by the following (it's white - that's why you can't visualize it here):
![OKFN-landscape-white-rgb](https://user-images.githubusercontent.com/8523847/217266708-179663c3-919f-4bc3-bc79-301dda9042c3.svg)

Please ping me if you have any questions!

Thank you!

**Comment by aivuk** [comment]
Hi @lucpretti, the svg file for the logo is a bit broken, see the screenshot below:

![Screenshot from 2023-02-07 17-09-50](https://user-images.githubusercontent.com/272892/217299304-25483892-ccf4-4cca-bf48-ad131b4e73ce.png)

I'm using the png version from the 2022.okfn.org

**Comment by lucpretti** [comment]
Ok, looks good. Thank you!
