### ISSUE TITLE
Add Event Date on map event cards

### ISSUE THREAD

**Issue by lucpretti** [okfn/opendataday#407]
As ODD is not anymore a day, but a week of events, many people are reaching out asking when the events displayed on the map are taking place. This information is available on the source spreadsheet. So please add a new line to the event card saying `Date:` before the `URL:` line and print the date informed by users.

![Screenshot 2024-02-23 at 18 56 32](https://github.com/okfn/opendataday/assets/8523847/54dff614-02d2-4773-b57a-cf319f2304c6)

**Comment by avdata99** [comment]
Fixed @lucpretti

We can see event dates now:

![image](https://github.com/okfn/opendataday/assets/3237309/c1b146dc-a84f-4d59-a2a2-cabc79e2f8e9)
