### ISSUE TITLE
get rid of the wiki. Merge content onto the main wiki.okfn.org

### ISSUE THREAD

**Issue by harry-wood** [okfn/opendataday#41]
I think it could be good to think about getting rid of the opendataday wiki. Merge content onto the the main wiki.okfn.org  (where necessary. There's actually not much very worthwhile content on the open data wiki anyway. Lots of pages documenting past events in an untidy confusing way. The only really useful thing is a single page list of events happening in 2015, which would very easily moved onto a wiki.okfn.org page)

Why do that? because a wiki community is a critical mass game. When it comes to things like getting people tidying things up and despamming and carefully restructuring things...  you need a few active users forming a community, and watching the recent changes page, and feeding off eachothers activity. It's like trying to start a fire. Often activity fizzles out quickly, but if you can get it to grow...

So trying to kindle two different fires (or more. Are there other mediawiki's still being used by OKFN?) makes it less likely to succeed.

**Comment by billymeinke** [comment]
Not starting a new issue, but chiming in that the CAPTCHA shown when creating new accounts on the ODD wiki is acting up. 7 tries later, I'm still getting CAPTCHA errors. Any chance this could be checked on? I'm trying to add our event in Honolulu to the wiki. Thanks!

**Comment by harry-wood** [comment]
*"Not starting a new issue"* why not? Please create a new issue if you have a new issue. This has nothing to do with my original issue.

Now I *would* be helpful and create a new issue for you, except that I can't see a problem. Account creation is working fine. Please describe your problem in a new issue github if you still see it.

**Comment by morchickit** [comment]
Done. We can create more pages on the new theme.
