### ISSUE TITLE
Fix map 

### ISSUE THREAD

**Issue by morchickit** [okfn/opendataday#97]
This is connected to user story 3 (issue #87 ). The map component helps to users to identify events in their area. Currently, the map is broken, and I am gathering all map related issues under this issue. 
The dataset for the map is located in this spreadsheet- https://docs.google.com/spreadsheets/d/1cV43fuzwy2q2ZKDWrHVS6XR4O8B01eLevh4PD6nCENE/edit#gid=1172400195

So far, it has been easy to add events with the spreadsheet, so we should keep it. 
 
- [ ] make the URL for each event clickable see  #53. 

- [x] The tiles in the map do not display anymore and point instead to this blog post. Make map to show events. See #84

**Comment by harry-wood** [comment]
The issues are related, but ... merging them into one issue seems odd. Anyway...

On the topic of the mapquest tiles, this tile server reference is buried in the "Recline" code vendored in this repo.  Looking at "recline" I see the issue has been tackled there: https://github.com/okfn/recline/issues/500  so probably would be solved here by updating Recline (however you do that)

**Comment by morchickit** [comment]
I added my rational for this + this is something that we did in other OKI project. @pwalsh can break it again to two if he wish.

**Comment by miles-dev** [comment]
I originally posted this to https://groups.google.com/forum/#!topic/open-data-day/vKqO_dmRKN0, but adding a note here as well:

Can we at Mapbox set you up with a free account to get maps working again on your site? If of interest, we'd also be up for provided comped accounts for the participants in the Hackathon who want to experiment with putting data on a map. Our information can be found at https://www.mapbox.com/. Please reach back out if this is of interest to you and we can help get you up and running.

**Comment by morchickit** [comment]
Great, thanks! This is a community-based project, so if you want to add code to the site with MapBox embedded map, feel free to send us a pull request.

**Comment by callmealien** [comment]
Hey @miles-dev, happy to use mapbox on the ODD site. Any way to read a dataset directly from google sheets on MapBox?

**Comment by miles-dev** [comment]
@callmealien - I'm not aware of a path straight from google sheets to Mapbox, but the easiest method to get the data over would be to export it to a csv and then upload it through the front end at https://www.mapbox.com/studio/datasets/. Since the spreadsheet has a lat/lon already in the file, the upload process should auto-pull those points out for you.

Some documentation on the upload process: https://www.mapbox.com/help/uploads/
Some documentation if you want to use the API/curl for the upload: 
* API docs: https://www.mapbox.com/api-documentation/#uploads
* Directions via curl: https://www.mapbox.com/help/upload-curl/

If I come across a way to go directly from google sheets I'll let you know.

**Comment by miles-dev** [comment]
@callmealien - As always happens when you post a response, I naturally found the solution to this just a few minutes later. There is an example with code and documentation which can be found here: https://www.mapbox.com/blog/data-driven-style-remote-sources/.

Thanks.

**Comment by harry-wood** [comment]
Surely the correct fix to this issue in this repository is to update 'recline'

**Comment by danfowler** [comment]
So, I have a basic map linking to events from a Google Sheet using mapboxgl:

![screen shot 2017-01-30 at 23 19 53](https://cloud.githubusercontent.com/assets/772616/22452188/aa830b50-e742-11e6-8cb3-246bdd56f602.png)

It could stand to look a bit nicer, though.

**Comment by miles-dev** [comment]
@danfowler - Looking good! Glad to see it's coming together. If it's helpful and of interest, a guide to styling in Mapbox can be found here: https://www.mapbox.com/help/studio-manual-styles/. It'll walk you through how to use Mapbox Studio to customize the map however you'd like.
