### ISSUE TITLE
Display translations of homepage prominently 

### ISSUE THREAD

**Issue by morchickit** [okfn/opendataday#98]
This issue is connected to issue #85 . Currently, the sidebar *does* link to different translations but it is not presented well on the site (user have to scroll down the sidebar to get to the appropriate language).

**Comment by HeidiSeibold** [comment]
Maybe it would be easier to be country specific instead of language specific?

**Comment by morchickit** [comment]
@HeidiSeibold I don't follow. Some rational -
1. Some language are relevant for more than one country (Spanish)
2. Homepage is relevant to *all* events as an intro. It is not connected to specific events.

**Comment by HeidiSeibold** [comment]
Aha so the homepage does not give any info on the events? Then language-specific would probably just as good. 

I thought that the events would be featured and then it would not make sense to group Mexico and Spain or the US and Britain together. 

If there won't be a wiki anymore and the hompeage does not say anything about the events, how will events be made public? How will you know how many events there are in total?

**Comment by HeidiSeibold** [comment]
I guess I was confused by the current version of http://de.opendataday.org/ which features only Germany but not Austria or Switzerland. I was expecting there to be a at.opendataday and an ch.opendataday in the future.

**Comment by morchickit** [comment]
This works well in the new site. Closing this.
